version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend-app:
    build:
      context: .
      args:
        NODE_VERSION: "16"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/users_data
      - REDIS_URL=redis://host.docker.internal:6379
